### ISSUE TITLE
Combine different platform repos into one?

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#2]
I noticed you had the Unix and Windows (and other) platform code all in separate repositories.

I don't have access to Android or IOS platforms but I do have access to Linux, Mac, and Windows platforms.

Would you accept a PR to combine the connector_unix and connector_windows repos into one?

I would also get them to build with CMAKE as it is cross platform across all those platforms.

If so, please let me know and I will try to make that happen.

**Comment by davidsummers** [comment]
PS. 

I'm *VERY* impressed with your program.

It took me several weeks to figure out how to get XLINK KAI to work (I'm using it on the Raspberry PI), but I finally got it working.

I tried your program for the first time a few minutes ago.

I had to make a couple of configuration changes on the CMAKE build I'm working on, but I then got it to compile on MacOS and Raspberry PI.

Then I ran it on the Raspberry PI.

IT  JUST WORKED (TM)

Out of the box, no configuration, no nothing.  All I did was start it up and I saw servers and connected and it worked.  I then connected my WarHawk Server and it "Just Works (TM)".

What I really liked (that I haven't been able to figure out how to do on XLINK KAI) is that it looks like I can run a WarhWawh Server 24x7 without having it disconnect after an hour or so like on XLINK KAI.

Awesome good program and good job!

**Comment by davidsummers** [comment]
Woops, I just now noticed that the Windows version is C# instead of C++.

I still think it could be built using CMAKE and brought into one repository.

**Comment by Thalhammer** [comment]
As you already noticed that the Windows version and the linux version use different Languages I am skipping this part. Thats the main reason why they are different repos.

That said I would really like to deprecate both Windows and Linux versions for either a cross plattform C++ version (fast and simple + static build to prevent dependency problems) or a cross plattform Java version (depends on Java, but could share code with the android client).

Neither Windows nor the Linux client support hosting and neither of them are pretty, so they really need to get redone.

Warhawk Reborn can't "disconnect" the way Xlink does as they are quite different. XLink is kind of a gaming optimized VPN and tunnels all traffic of your PS3. Doing so has a couple of drawbacks:
* The client needs to run all time
* It might add latency
* Its complicated to set up
* **It kills PSN and Internet connectivity on the PS3**
* It requires a PC

Warhawk reborn works different:
It responds to the packets sent during game discovery and replaces the host IP address with the real hosts public IP. Turns out the game just accepts that and connects directly to the server. This adds a small one time cost for people hosting (need to forward a port to PS3) but decreases the cost for every one just playing to basically plug and play. You can keep the client running but theres no need to (but it does not harm either).

**Comment by davidsummers** [comment]
So it sounds like maybe you are leaning more towards getting the unix version running on Windows instead of trying to combine the two different language implementations into one repo?

I could work on that if you would accept my PRs for doing that.  I work on a lot of cross-platform code and enjoy doing that kind of thing.

I've already got CMAKE working to build on MacOS and Raspberry PI in my fork of your repo.  I could continue on and see if I could get it working on Windows and make changes to accomplish that if needed.   Usually it is not a whole lot of differences, and even less now that there is more standardized support for stuff in the new versions of the C++ language.

If that is acceptable to you then I could continue forward with the goal of having you accept my PRs into your code.

Thoughts?

**Comment by davidsummers** [comment]
What about if I tried a separate port of the Android Version to current C++ (Standard C++ 17), since the Android version has the full set of current capabilities....   ???

That seems the best way forward to me, at the current time.

The C++ versions currently seem to have dependencies on CURL and OPENSSL, so those would be needed on a Windows platform, but already available on a Linux or Mac platform.

Hmmm.....very interesting.....

**Comment by Thalhammer** [comment]
My original idea was to port the unix version to windows (should be pretty simple) and implement a small webserver in it to serve a UI. This would have some benefits over a native gui app:
* Ability to use UI from a different device than host
* Run on headless without modifications
* Plattform independent gui design

**Comment by davidsummers** [comment]
OK, well, I think I will try working on the port of the current Unix to Windows (I've already started that process) and then I would really like to get the Unix/Windows code to be able to do the hosting feature that the Android version has.

I'll keep in mind your items above,

- Ability to use UI from a difference device than host
- Run on headless without modifications
- Platform independent gui design.

**Comment by davidsummers** [comment]
Please see PR #4 for the first try at:

1. CMAKE
2. Porting to Windows
3. Rename executable from 'bridge' to 'warhawk-reborn'.

**Comment by davidsummers** [comment]
CMAKE branch was merged.

Closing issue.

**Comment by davidsummers** [comment]
By the way, I've got binaries for:

1. Windows
2. MacOS
3. Raspberry PI
4. CentOS 7

at

https://summersoft.fay-ar.us/pub/games/warhawk URL.
